name: Deploy to Docker Hub to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push crear microservice
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/crear:${{ github.sha }} ./crear
          docker push ${{ secrets.DOCKER_USERNAME }}/crear:${{ github.sha }}

      - name: Build and push leer microservice
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/leer:${{ github.sha }} ./leer
          docker push ${{ secrets.DOCKER_USERNAME }}/leer:${{ github.sha }}

      - name: Build and push actualizar microservice
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/actualizar:${{ github.sha }} ./actualizar
          docker push ${{ secrets.DOCKER_USERNAME }}/actualizar:${{ github.sha }}

      - name: Build and push eliminar microservice
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/eliminar:${{ github.sha }} ./eliminar
          docker push ${{ secrets.DOCKER_USERNAME }}/eliminar:${{ github.sha }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/crear:${{ github.sha }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/leer:${{ github.sha }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/actualizar:${{ github.sha }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/eliminar:${{ github.sha }}

            # Aquí puedes agregar los comandos para ejecutar los contenedores
            docker run -d --name crear ${{ secrets.DOCKER_USERNAME }}/crear:${{ github.sha }}
            docker run -d --name leer ${{ secrets.DOCKER_USERNAME }}/leer:${{ github.sha }}
            docker run -d --name actualizar ${{ secrets.DOCKER_USERNAME }}/actualizar:${{ github.sha }}
            docker run -d --name eliminar ${{ secrets.DOCKER_USERNAME }}/eliminar:${{ github.sha }}
          EOF

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/crear:${{ github.sha }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/leer:${{ github.sha }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/actualizar:${{ github.sha }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/eliminar:${{ github.sha }}

            # Ejecutar contenedores con los puertos correctos
            docker run -d --name crear -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/crear:${{ github.sha }}
            docker run -d --name leer -p 5001:5001 ${{ secrets.DOCKER_USERNAME }}/leer:${{ github.sha }}
            docker run -d --name actualizar -p 5002:5002 ${{ secrets.DOCKER_USERNAME }}/actualizar:${{ github.sha }}
            docker run -d --name eliminar -p 5003:5003 ${{ secrets.DOCKER_USERNAME }}/eliminar:${{ github.sha }}
          EOF
